### ISSUE TITLE
Don't change the default user within the container

### ISSUE THREAD

**Issue by gcarre** [jenkinsci/oki-docki-plugin#13]
oki-docki runs commands as the user the jenkins slave is running as, not as the default user configured in the docker image.

Here are a couple examples of issues that this behavior is causing in a job where the default user in the docker image is `root`:
- I added a pre-build step to start mysql: `service mysql start`. This command doesn't work if the user is not root
- My maven build needs a custom `~.m2/settings.xml`, the `jenkins` user in the container doesn't have this file

So, I could fix this by setting up the jenkins user in my container, but if I want to use a different Jenkins slave tomorrow that runs as another user, I'll have to fix my container again right?

I think the responsibility of choosing which user to run commands as in the container should be left to the container maintainer, not to oki-docki.

**Comment by ndeloof** [comment]
Changing the user is required so the file written to build workspace are readable back outside the container.

**Comment by calvinatintel** [comment]
I agree with the OP. Docker containers are used for setting up a **pre-defined environment** - a user is a critical part of this environment. May containers will simply not work unless it's running as the user set up by the container.

The workspace content indeed needs to be readable back outside the container. For that, we can `chown -R $user:$group .` before exiting.

**Comment by ndeloof** [comment]
running chown on a large workspace would slow down the build. I don't get the requested use-case. 

- "I added a pre-build step to start mysql: service mysql start." you should use a second container to run test services and link them to build container. This is not (yet) supported by oki-docki, contributions are welcome !
- "My maven build needs a custom ~.m2/settings.xml". Just like on a classic slave node, use config-file-provider plugin or comparable

**Comment by calvinatintel** [comment]
[Best practices for writing Dockerfiles](https://docs.docker.com/articles/dockerfile_best-practices/#user) states: 
> If a service can run without privileges, use `USER` to change to a non-root user. Start by creating the user and group in the `Dockerfile` with something like `RUN groupadd -r postgres && useradd -r -g postgres postgres`.

I read that as a recommendation to explicitly manage the user who will run the `CMD`, whether it be `root` or a non-root user like postgres in the example. Since it's recommended to specify a user in `Dockerfile`, it makes sense to preserve the user rather than override it.

Further, [Docker run reference](https://docs.docker.com/reference/run/#user) states (emphasis mine):
>The default user within a container is root (id = 0), but **if the developer created additional users**, those are accessible too.

It sounds like `-u` is intended for accessing the non-root users predefined by the `Dockerfile` creator. In that context, using `-u` to become `jenkins` user in the container is incorrect since the container will not have `jenkins` user in most cases.

**Comment by calvinatintel** [comment]
I hope I didn't sound too critical. Thank you for the excellent plugin - I've noticed the same shortcomings of Docker Plugin as you did.

Since -u is an option provided by docker, I believe it's okay to have an option to use it however you desire. If I had it my way, each of the `docker run` options will be exposed to the user on Jenkins so that they can be configured.

**Comment by ndeloof** [comment]
@calvinatintel the docker documentation doesn't tell there's no user mapping between host and container - especially on filesystem - so if your docker container creates file as user xxx you can't read them outside the container without being root - I'd be ok to support `--user` when docker do introduce user namespace. Please remember we need Jenkins post-build actions to be able to access the workspace to archive artifacts, consume reports, etc.

**Comment by ndeloof** [comment]
also, -u is not intended for accessing non-root users predefined by the Dockerfile. If Dockerfile has a `USER` command, then all subsequent commands (including those ran when container start) do run as this user.

**Comment by ndeloof** [comment]
also see https://github.com/docker/docker/issues/7198

**Comment by calvinatintel** [comment]
I agree that not overriding the user to jenkins will render the files unreadable, and that `chmod -R $UID:$GID .` is slow.

On Issue 7198, the discussion is moving towards different way of mounting the volumes to handle the ownership, rather than changing the running user. I agree with this direction.

How about making it an option, since many containers break with `-u $UID`?

**Comment by ndeloof** [comment]
:-1: until one show me a concrete use-case to require a specific user in a Build container.

**Comment by gcarre** [comment]
I think most users who are going to test your plugin will start from a
container they already have, that's what I did.

Then they will realize they need to create a jenkins user in the docker
container, which is confusing because even you wrote this on the plugin
homepage: "*without any prerequisites on the Docker image*".

That's what happened to me anyway, and it was a bit confusing.

On Wed, Mar 25, 2015 at 9:11 AM, Nicolas De loof <notifications@github.com>
wrote:

> [image: :-1:] until one show me a concrete use-case to require a specific
> user in a Build container.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/oki-docki-plugin/issues/13#issuecomment-86099502>
> .
>



-- 
Guillaume Carré

**Comment by ndeloof** [comment]
yes indeed, that's what I expect : use the same Dockerfile you use for development

You don't NEED to create this user in the docker image. As long as you access workspace resources for the build and have adequate packages/tools install for all users, you're all set. Just consider a guest user to log into your box and use same tools to build.

Can you please describe what you put in your Dockerfile that would require to know the user  who run the build ?

**Comment by gcarre** [comment]
I don't need to create the jenkins user in the docker image? How will "`-u jenkins`" work if the `jenkins` user doesn't exist in the docker image?

I put a couple examples in this issue description, in my existing docker file I run a shell script that starts mysql and then start maven commands that require a custom `.m2/settings.xml`. To keep it simple I run it with the root user (default docker user).

So to make it work with oki-docki I would need to:
* create the `jenkins` user
* give it sudo rights to start/stop mysql
* copy the custom `.m2/settings.xml` to the jenkins user home folder

Or am I missing something?

**Comment by calvinatintel** [comment]
In my experience, `-u jenkins` run as an unnamed user with UID of 107. As you can guess, jenkins user has UID 107 on the host machine.

However, `whoami` breaks since the user is unnamed in the container:

    $ docker exec -t 535114cb55e675d25e3c0736a3e8956efb94e6e6b446802d1d1b89b8c484d9ac /bin/sh -xe /tmp/hudson2431249589756823557.sh
    + set -v
    echo "Hello!"
    + echo 'Hello!'
    Hello!
    whoami
    + whoami
    whoami: cannot find name for user ID 107
    Build step 'Execute shell' marked build as failure

**Comment by ndeloof** [comment]
indeed, user to exist with same uid as define on host.
I don't think "whoami" is a useful command for a build script, I can live with this limitation :P
