### ISSUE TITLE
Customizable build processes

### ISSUE THREAD

**Issue by Julian** [jenkinsci/oki-docki-plugin#17]
For our jobs, we need to build some dependencies and then volume them into the built container for the image to install. It would be nice if there was a way to provide arbitrary options to `docker build` (probably  even nicer if there was specific support for volumes but still there would likely be a use case for arbitrary options).

It also would be nice if there was a possibility to have that pre-build step in the job (we use the Env Inject plugin, and I sort of expected at least that part to happen on the host machine, but it seems like even that is attempted within the container).

Any thoughts about either of those use cases?

**Comment by ndeloof** [comment]
The docker-way to handle this is for any dependency to be present in the docker build context directory, aside the Dockerfile

**Comment by Julian** [comment]
Right :). Which is why it'd be nice to be able to do so -- the way the plugin works right now, you can't, since there's no way to run things on the host before the container is built.

**Comment by ndeloof** [comment]
I'm working on a build step wrapper (same as conditional build step plugin) so you can run a group of build steps inside a container, but also have more classic builds steps before/after

**Comment by Julian** [comment]
Ah cool, I'll look out for it, thanks!
